# config/config.yaml

# OpenAI API Configuration
openai:
  api_key_env_var: "openai_api_key"
  model: "gpt-4o-mini" 
  system_message: "You are an expert penetration tester and cybersecurity officer. You help with your vast knowledge of vulnerabilities. You will alwas answer exactly as the user requests."

# Excel File Configuration
excel:
  input_path: "data/file.xlsx"
  sheet_name: "Sheet1"

# Column Mapping Configuration
columns:
  input:
    - "Vulnerability"
    - "Description"
  output:
    Risk Category:
      prompt: "Analyze the vulnerability details and determine its Risk Category based on the CIA Triad. Select one or more of the following: Confidentiality (C), Integrity (I), or Availability (A), and explicitly label the output with the appropriate letter(s): C, I, A."
      max_tokens: 10
      temperature: 0.1
      fetch_all: true
      schema:
        name: "risk_category"
        schema:
          type: "object"
          properties:
            risk_level:
              type: "string"
              enum: ["C", "I", "A", "C I", "C A", "I A", "C I A"]
          required: ["risk_level"]
          additionalProperties: false
    Exploitability:
      prompt: "Read the following vulnerability details carefully, and then assess the exploitability of the vulnerability. Using your Penetration Testing expertise, indicate the difficulty for this vulnerability to be exploited. Provide your assessment in one word, and only one of the following categories explicitly: Easy, Medium, Hard."
      max_tokens: 10
      temperature: 0.1
      fetch_all: true
      schema:
        name: "exploitability"
        schema:
          type: "object"
          properties:
            difficulty:
              type: "string"
              enum: ["Easy", "Medium", "Hard"]
          required: ["difficulty"]
          additionalProperties: false
    Impact:
      prompt: "Read the following vulnerability details carefully, then, without an introduction to the vulnerability or mentioning its name, provide a simple and concise impact description for the vulnerability, without using headers, just normal text, on how it can affect a client."
      max_tokens: 150
      temperature: 0.7
      fetch_all: true

# Processing Configuration
processing:
  sleep_time: 1
  retry_attempts: 2
  retry_delay: 3
