# config/config.yaml

# OpenAI API Configuration
openai:
  api_key_env_var: "openai_api_key"
  model: "gpt-4o-mini"
  system_message: "You are an expert penetration tester and cybersecurity officer. You help with your vast knowledge of vulnerabilities. You will always answer exactly as the user requests."

# Excel File Configuration
excel:
  input_path: "data/Output.xlsx"
  sheet_name: "Main Vulns"

# Filtering Configuration
filter:
  enabled: false  # Toggle to enable or disable filtering
  criteria:
    - column: "Severity"
      operation: "in" # Supported operations: equals, contains, in, greater_than, less_than
      value: ["Critical", "High", "Medium", "Low"]

# Column Mapping Configuration
columns:
  output:
    Risk Category:
      input_columns:
        - "Vulnerability"
        - "Description"
        - "Impact"
      prompt: "Analyze the vulnerability details carefully and determine its Risk Category based on the CIA Triad. Select one or more of the following: Confidentiality (C), Integrity (I), or Availability (A), and explicitly label the output with the appropriate letter(s): C, I, A."
      max_tokens: 10
      temperature: 0.1
      fetch_all: false
      schema:
        name: "risk_category"
        schema:
          type: "object"
          properties:
            risk_level:
              type: "string"
              enum: ["C", "I", "A", "C I", "C A", "I A", "C I A"]
          required: ["risk_level"]
          additionalProperties: false
    Exploitability:
      input_columns:
        - "Vulnerability"
        - "Description"
        - "Impact"
      prompt: >
        Based on the provided vulnerability information, rank the exploitability of each vulnerability. Consider the following factors when making your assessment:
        1. Is the output worth the trouble of exploiting it?
        2. Ease of exploitation (Is it simple or complex to exploit?) (Does it require user interaction or not?)
        3. Technical expertise required (Can a novice exploit this, or does it require advanced skills?)
        4. Potential impact (What damage can exploitation cause, such as system control or data exposure?)

        For each vulnerability, analyze the name, description, and impact to determine one of the following levels of exploitability:

        High: Easy to exploit, requires minimal access or knowledge, widely available exploit tools, deals great damage.
        Medium: Requires some expertise, access, or custom tools, deals moderate damage, but feasible in most cases.
        Low: Difficult to exploit, or requiring specific conditions, expertise, or access that is unlikely. Or the output is not really worth the effort of exploiting.
      max_tokens: 10
      temperature: 0.1
      fetch_all: false
      schema:
        name: "exploitability"
        schema:
          type: "object"
          properties:
            exploitability:
              type: "string"
              enum: ["Low", "Medium", "High"]
          required: ["exploitability"]
          additionalProperties: false

# Processing Configuration
processing:
  sleep_time: 0.2
  retry_attempts: 2
  retry_delay: 3
